### ISSUE TITLE
postFlush in LogRevisionsListener does not account for reserved SQL terms

### ISSUE THREAD

**Issue by Rezaldy** [dave-redfern/laravel-doctrine-entity-audit#5]
Hi! It's me again. I have another thing I ran into. We have a Product table that has a nullable field called `Default`. Aaaand `default` happens to be a keyword in SQL too, so I believe it is failing on this.

> An exception occurred while executing 'UPDATE revision_audit_Product SET default = ? WHERE rev = ? AND id = ?' with params [null, "26", redacted]:SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'default = NULL WHERE rev = '26' AND id = redacted' at line 1

This only happens with this specific tables. All revisions on all other tables are logged correctly.

**Comment by Rezaldy** [comment]
Just found another table that has an "order" column to specify in what order they should be shown. Order is also a reserved SQL term. :disappointed:

**Comment by dave-redfern** [comment]
@Rezaldy thanks for the report; I'll add escaping to column names. I think that the platform is directly available in the listener so should be pretty straight forward.

**Comment by dave-redfern** [comment]
@Rezaldy not quite so straight forward! It was needed in a few places and then I ran into a separate issue where the Doctrine schema builder wasn't escaping the mapped column names in my test case; but it should be fixed in 0.7.3.

**Comment by Rezaldy** [comment]
Ah, I see! Thank you so much Dave!
